### ISSUE TITLE
Can't use package anymore

### ISSUE THREAD

**Issue by bojant987** [voodoos/bs-semantic-ui-react#2]
npm ERR! bs-semantic-ui-react@0.2.0 install: `./node_modules/bs-platform/lib/bsb -make-world`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bs-semantic-ui-react@0.2.0 install script.

I think this might be due to adding of "install": "./node_modules/bs-platform/lib/bsb -make-world" script which overwrites default npm install and during package installation when npm runs "npm install" it's trying to run a file inside node_modules but node_modules don't exist at the time because now there's no script to install deps.

**Comment by voodoos** [comment]
Sorry, I removed it !
